name: Spec Released

on:
  # This workflow is triggered whenever a new version of the substrait specification is released
  repository_dispatch:
    types: [spec-released]

jobs:
  handle-spec-release:
    uses: ./.github/workflows/publish_artifacts.yml
    secrets: inherit
    with:
      substrait_version: ${{ github.event.client_payload.substrait_version }}
